name: Test

on:
    pull_request:
        branches:
            - main

jobs:
    test:
      runs-on: ubuntu-latest

      timeout-minutes: 5

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run test.sh
          run: podman run hooklinesecureimage:0.1 bash -c "./test.sh"
